header:
    base_game_version: '' # Optional
    description: '' # Optional
    lock_template_options: '' # Optional, used for world templates
    min_engine_version: ''  # Mandatory
    name: ''  # Mandatory
    uuid: ''  # Mandatory
    version: '' # Mandatory