name: CMake

on:
    push:
        branches: ['main']
    pull_request:
        branches: ['main']

env:
    BUILD_TYPE: Release

jobs:
    build:
        runs-on: windows-latest

        steps:
            - uses: actions/checkout@v4
              with:
                submodules: true

            - name: Configure CMake
              run: cmake -S . -B build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DGITHUB_ACTION=ON

            - name: Build
              # Build your program with the given configuration
              run: cmake --build build --config ${{env.BUILD_TYPE}} --parallel

            - name: Run Tests
              working-directory: ${{github.workspace}}/build
              run: ctest -C ${{env.BUILD_TYPE}} --rerun-failed --output-on-failure
